apiVersion: v1
kind: Service
metadata:
  name: training-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: training-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
