apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-app
  labels:
    app: training-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: training-app
  template:
    metadata:
      labels:
        app: training-app
    spec:
      containers:
        - name: training-app
          image: "{{ .Values.image.trainclu.registry }}/{{ .Values.image.trainclu.repository }}:{{ .Values.image.trainclu.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config.json
              subPath: config.json
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: config-volume
          configMap:
            name: training-app-config
